algoritmo "semnome"
var
   ValorE, parc, parcela, vjuros,total :Real
inicio
      Escreva ("Quanto você quer pegar de emprestimo? R$")
      Leia (ValorE)
      vjuros <-   ValorE*(20/100)
      total <- Vjuros + valorE
      Escreval (" Em quantas vezes gostaria de parcelar seu emprestimo? ")
      Leia (parc)
      parcela <- total/parc
      Escreva ("Seu emprestimo ficará no valor de R$",total ," com",parc," parcelas de R$", parcela)
fimalgoritmo
